.TH "zrepchr.h" 3 "Thu Jan 2 2020" "zString" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zrepchr.h \- Header file for zrepchr function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBzrepchr\fP (char *str, char x, char y)"
.br
.RI "Replaces a character with another one\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file for zrepchr function\&. 

Functions defined in this file can be distributed under the 2-Clause BSD license\&. 
.PP
\fBCopyright\fP
.RS 4
2016-2019, Fehmi Noyan ISI 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "char* zrepchr (char * str, char x, char y)"

.PP
Replaces a character with another one\&. Every occurance of the character given by the argument \fCx\fP contained in the first argument \fCstr\fP is replaced by the character given by the argument \fCy\fP\&.
.PP
\fBParameters\fP
.RS 4
\fIstr\fP pointer to the input string 
.br
\fIx\fP the character to be replaced 
.br
\fIy\fP the character that will replace the character given by \fCx\fP 
.RE
.PP
\fBExample\fP 
.PP
.nf
#include <stdio\&.h>
#include <zstring\&.h>

int main() {
     char s[]="this is a random string to test the function\&.";
     char x=' ', y='_';
     printf("%s\n",zrepchr(s,x,y));
     return 0;
}

.fi
.PP
.PP
\fBOutput\fP 
.PP
.nf
this_is_a_random_string_to_test_the_function\&.

.fi
.PP
.PP
\fBReturns\fP
.RS 4
zrepchr function returns a pointer to the resulting string\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for zString from the source code\&.
