.TH "zstring.h" 3 "Thu Jan 2 2020" "zString" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zstring.h \- Main header file for zString library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'zstrchr\&.h'\fP
.br
\fC#include 'zrmvchr\&.h'\fP
.br
\fC#include 'zstrtok\&.h'\fP
.br
\fC#include 'zstrtok_d\&.h'\fP
.br
\fC#include 'zrepchr\&.h'\fP
.br
\fC#include 'zrepstr\&.h'\fP
.br
\fC#include 'zsubstr\&.h'\fP
.br
\fC#include 'zstrtrm\&.h'\fP
.br
\fC#include 'zstrtrm_l\&.h'\fP
.br
\fC#include 'zstrtrm_r\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBZSTRING_VER\fP   '1\&.9'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main header file for zString library\&. 

You can include this file in your source or individual header file for the function you are using\&. All the functions defined in this library can be distributed under the 2-Clause BSD license\&. 
.PP
\fBCopyright\fP
.RS 4
2012-2019, Fehmi Noyan ISI 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for zString from the source code\&.
